name: Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection and generate report
        run: |
          newman run e2e-tests/api-tests/postman_collections/Employees.postman_collection.json \
            --reporters cli,html \
            --reporter-html-export e2e-tests/api-tests/newman/newman-report.html

      - name: Verify report file location
        run: ls -la e2e-tests/api-tests/newman

      - name: Upload Newman Reports
        uses: actions/upload-artifact@v3
        with:
          name: newman-reports
          path: e2e-tests/api-tests/newman/*.html
