name: Cypress Tests

on:
  push:
    branches:
      - main
    paths:
      - 'e2e-tests/ui-tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'e2e-tests/ui-tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to e2e-tests/ui-tests
        run: cd e2e-tests/ui-tests

      - name: Install dependencies
        run: npm install
        working-directory: e2e-tests/ui-tests

      - name: Run Cypress tests
        run: npm run test
        working-directory: e2e-tests/ui-tests
